### ISSUE TITLE
2 Errors

### ISSUE THREAD

**Issue by RuggieroB** [EnricoRuggieroB/Java_Scuola#1]
Gentile Prof. Tessitore;
Le faccio una proposta indecente: Potrebbe aiutare questo scocciatore per i programmi "ContoCorrente1" e "ContoCorrente2"? Il primo  da 2 errori: "ContoCorrente1.java:31: error: constructor ContoCorrente in class ContoCorrente cannot be applied to given types;
		ContoCorrente cc = new ContoCorrente (32000.00 , 455347);
		                   ^
  required: double
  found: double,int
  reason: actual and formal argument lists differ in length
ContoCorrente1.java:61: error: cannot find symbol
				System . out . println ( " \n Numero di conto corrente: \t " + cc . numero );
				                                                                  ^
  symbol:   variable numero
  location: variable cc of type ContoCorrente
2 errors"
Saprebbe aiutare il Sottoscritto ed il Prof. Campetiello?

Mille grazie
ERBB

**Comment by RuggieroB** [comment]
@FabioZTessitore

**Comment by RuggieroB** [comment]
> Gentile Prof. Tessitore;
> Le faccio una proposta indecente: Potrebbe aiutare questo scocciatore per i programmi "ContoCorrente1" e "ContoCorrente2"? Il primo da 2 errori: "ContoCorrente1.java:31: error: constructor ContoCorrente in class ContoCorrente cannot be applied to given types;
> ContoCorrente cc = new ContoCorrente (32000.00 , 455347);
> ^
> required: double
> found: double,int
> reason: actual and formal argument lists differ in length
> ContoCorrente1.java:61: error: cannot find symbol
> System . out . println ( " \n Numero di conto corrente: \t " + cc . numero );
> ^
> symbol: variable numero
> location: variable cc of type ContoCorrente
> 2 errors"
> Saprebbe aiutare il Sottoscritto ed il Prof. Campetiello?
> 
> Mille grazie
> ERBB

@FabioZTessitore

**Comment by FabioZTessitore** [comment]
il costruttore di ContoCorrente accetta un solo parametro, il saldo iniziale, mentre ne passi due nel main

**Comment by RuggieroB** [comment]
Ah... grazie.
Però nell’altra classe, passo due parametri.
Cerco una soluzione........
Mille grazie 

Buona giornata 
Lo Scocciatore



Inviato da Libero Mail per iOS


mercoledì 20 febbraio 2019, 11:54 +0100 da notifications@github.com  <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
la classe ContoCorrente2 non ha il costruttore (manca il 2 finale) e nel main fai riferimento a ContoCorrente.
Stai facendo confusione con le classi

**Comment by RuggieroB** [comment]
Misericordia!
Si, forse sono un po’ troppo confusionario...
Cerco di sistemare, allora

Ancora grazie per aver accettato la mia proposta indecente 


Inviato da Libero Mail per iOS


mercoledì 20 febbraio 2019, 12:10 +0100 da notifications@github.com  <notifications@github.com>:
