### ISSUE TITLE
file class

### ISSUE THREAD

**Issue by FabioZTessitore** [EnricoRuggieroB/Java_Scuola#2]
non dovresti caricare i file class

**Comment by RuggieroB** [comment]
Non lo sapevo. Anche qui .gutignore oppure esiste un altro genere di file?



Inviato da Libero Mail per iOS


lunedì 18 marzo 2019, 11:38 +0100 da notifications@github.com  <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
Si

Il lun 18 mar 2019, 13:29 EnricoRuggieroB <notifications@github.com> ha
scritto:

**Comment by RuggieroB** [comment]
Non appena rifaremo Manjaro, correggerò 
Buon Pomeriggio 



Inviato da Libero Mail per iOS


lunedì 18 marzo 2019, 13:45 +0100 da notifications@github.com  <notifications@github.com>:
